Origin/feature/nestjs migration/request implementation
DesApp-2024c2-Grupo-4/pedidos-materiales-de-laboratorio-backend pull request #5
Opened 2024-09-05 01:30 UTC by miuds22

ready for review

2024-09-05 01:57 UTC, lguerci-unahur requested changes

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.controller.ts
> +        return this.EquipmentService.getEquipment(description);
esta bien que haga un get de equipos en este endpoint?

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.controller.ts
> +    GetEquipmentById(@Param('id') id: number)
para los ids utilicemos el tipo `Type.ObjectId` de mongoose

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.controller.ts
> +        return this.EquipmentService.deleteEquipoById(id);
para los ids utilicemos el tipo Type.ObjectId de mongoose

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.controller.ts
> +    UpdateEquipmentById(@Param('id') id: number, @Body() equipment: Equipment)
para los ids utilicemos el tipo `Type.ObjectId` de mongoose

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.service.ts
> +export class EquipmentService {
Separar la lógica de los endpoints de  las llamadas a la db (ver conversation)

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.service.ts
> +  async createEquipment(equipment: Equipment): Promise<Equipment> {
agregar error handling

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.service.ts
> +  async getEquipments(): Promise<Equipment[]> {
que te parece si pasamos available como parametro y lo damos cómo opcional en el endpoint como `?available=true` ? De esa forma podríamos dejar que el front pueda listar solo los disponibles o todos

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.service.ts
> +    return equipments;
validar si no se obtuvo ningun equipo y retornar 404

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.service.ts
> +    return equipments;
validar si no se obtuvo ningun equipo y retornar 404

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.service.ts
> +    return equipment;
validar si no se obtuvo ningun equipo y retornar 404

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.service.ts
> +    return equipment; // TODO: Check how return the updated equipment with the last changes
on hace falta retornar el objeto actualizado, simplemente podes devolver el 200 vacio

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.service.ts
> +    return `Equipment with description ${equipment.description} and id ${equipment.id} was deleted successfully`;
no hace falta devolver un mensaje, con el 200 de la respuesta es suficiente

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.controller.ts
> +    @Post('/')
quitar los `'/'` de todos los endpoints que no tengan un subpath, por ejemplo en este caso quedaría `@Post()` solamente

2024-09-05 01:57 UTC, lguerci-unahur commented on src/equipment/equipment.controller.ts
> +    @Post('/')
En el caso de la creación de un nuevo elemento, se tiene como estandard devolver el HTTP status code 201, esto se puede hacer con decoradores en nest

2024-09-05 13:49 UTC, lguerci-unahur commented on .env-EXAMPLE
> -# APP
por que borramos este archivo?

2024-09-05 20:42 UTC, miuds22 commented on .env-EXAMPLE
> -# APP
perdon!. le saque el example para conectarlo a mi db  y probar

2024-09-05 20:50 UTC, miuds22 commented on src/equipment/equipment.controller.ts
> +        return this.EquipmentService.getEquipment(description);
asi esta en el codigo original

2024-09-05 20:50 UTC, miuds22 commented on src/equipment/equipment.controller.ts
> +    GetEquipmentById(@Param('id') id: number)
resuelto

2024-09-05 20:50 UTC, miuds22 commented on src/equipment/equipment.controller.ts
> +        return this.EquipmentService.deleteEquipoById(id);
resuelto

2024-09-05 20:50 UTC, miuds22 commented on src/equipment/equipment.controller.ts
> +    UpdateEquipmentById(@Param('id') id: number, @Body() equipment: Equipment)
resuelto

2024-09-06 13:38 UTC, lguerci-unahur commented on src/equipment/equipment.controller.ts
> +        return this.EquipmentService.getEquipment(description);
por eso hablamos de no migrar código, si no funcionalidades

2024-09-11 02:07 UTC, miuds22 commented on src/equipment/equipment.controller.ts
> +        return this.EquipmentService.getEquipment(description);
me imagino que esto debe realizar busqueda de equipos.

2024-09-11 02:11 UTC, miuds22 commented on src/equipment/equipment.service.ts
> +  async createEquipment(equipment: Equipment): Promise<Equipment> {
donde?

2024-09-11 02:11 UTC, miuds22 commented on src/equipment/equipment.service.ts
> +  async getEquipments(): Promise<Equipment[]> {
me copa la idea

2024-09-11 02:12 UTC, miuds22 commented on src/equipment/equipment.service.ts
> +  async getEquipments(): Promise<Equipment[]> {
pero propongamoslo como mejora. pensemoslo en el para que lo necesitamos.

2024-09-11 13:45 UTC, lguerci-unahur requested changes

2024-09-11 13:45 UTC, lguerci-unahur commented on src/equipment/equipment.controller.ts
> +        return this.EquipmentService.getEquipment(description);
es que buscar por description no me parece util, diria quitar esto

2024-09-11 13:45 UTC, lguerci-unahur commented on src/equipment/equipment.service.ts
> +        (err as Error).message,
en este caso no existe error, si no hubiese entrado al if anterior, retornemos un string vacio

2024-09-11 13:45 UTC, lguerci-unahur commented on src/equipment/equipment.service.ts
> +    if(equipments.length == 0)
en JS existe el concepto de "falsy" por ejemplo un array vacio, un objeto vacio, un string vacio, al realizar una operacion lógica, todos devuelven falso, por lo que esta validación puede hacerse como
`if(!equipments){`

2024-09-11 13:45 UTC, lguerci-unahur commented on src/equipment/equipment.service.ts
> +    return HttpStatus.CREATED
los status no se devuelven de esta forma, si no con decoradores en el controller, no hay que retornar nada en esta funcion

2024-09-11 13:45 UTC, lguerci-unahur commented on src/equipment/equipment.service.ts
> +    const [newequipment , err ] = await   handlePromise(this.dbEquipment.createEquipment(equipment))
en este caso newEquipment no es necesario podemos obviarlo directamente
` const [, err ] = await   handlePromise(this.dbEquipment.createEquipment(equipment))`

2024-09-11 13:45 UTC, lguerci-unahur commented on src/equipment/equipment.controller.ts
> +         let status = this.EquipmentService.updateEquipmentById(id,equipment);
el status no se devuelve de esta forma, retornemos directamente el resultado de la fn
`return this.EquipmentService.updateEquipmentById(id,equipment);`

2024-09-12 16:07 UTC, miuds22 commented on src/equipment/equipment.controller.ts
> +    @Post('/')
listo

2024-09-12 16:11 UTC, miuds22 commented on src/equipment/equipment.controller.ts
> +        return this.EquipmentService.getEquipment(description);
oki

2024-09-12 21:35 UTC, lguerci-unahur approved these changes

2024-09-12 22:06 UTC, merged